t.same(warnings, ['zlib: incorrect data check'])