{
    "cve_id": "CVE-2022-23948",
    "cve_description": "A flaw was found in Keylime before 6.3.0. The logic in the Keylime agent for checking for a secure mount can be fooled by previously created unprivileged mounts allowing secrets to be leaked to other processes on the host.",
    "cve_publish_date": "2022-09-21",
    "cwe_id": "NVD-CWE-noinfo",
    "cwe_name": "Insufficient Information",
    "cwe_description": "There is insufficient information about the issue to classify it; details are unkown or unspecified.",
    "commit_message": "secure_mount: use /proc/self/mountinfo\n\nThe function `check_mounted()` is parsing the output of the `mount`\ncommand.  This command can have an unknown number of spaces, that can\nbreak the parsing logic (and produces security issues)\n\nThis commit take the mount information data from `/proc/self/mountinfo`,\nthat is more friendly parsed as it will escape the spaces.\n\nSigned-off-by: Alberto Planas <aplanas@suse.com>",
    "type_of_change": "Modification",
    "filename_of_changes": "secure_mount.py",
    "code_language": "Python",
    "number_of_lines_added_for_mitigation": "36",
    "number_of_lines_deleted_vulnerable_to_cve": "20",
    "vulnerable_lines": [
        "// Line_Reference 16:     whatsmounted = cmd_exec.run(\"mount\")['retout']",
        "// Line_Reference 17:     whatsmounted_converted = config.convert(whatsmounted)",
        "// Line_Reference 18:     for line in whatsmounted_converted:",
        "// Line_Reference 19:         tokens = line.split()",
        "// Line_Reference 20:         tmpfs = False",
        "// Line_Reference 21:         if len(tokens) < 3:",
        "// Line_Reference 22:             continue",
        "// Line_Reference 23:         if tokens[0] == 'tmpfs':",
        "// Line_Reference 24:             tmpfs = True",
        "// Line_Reference 25:         if tokens[2] == secdir:",
        "// Line_Reference 26:             if not tmpfs:",
        "// Line_Reference 27:                 logger.error(\"secure storage location %s already mounted \"",
        "// Line_Reference 28:                              \"on wrong file system type: %s.  Unmount to\"",
        "// Line_Reference 29:                              \"continue.\", secdir, tokens[0])",
        "// Line_Reference 30:                 raise Exception(",
        "// Line_Reference 31:                     f\"secure storage location {secdir} already mounted on \"",
        "// Line_Reference 32:                     f\"wrong file system type: {tokens[0]}.  Unmount to \"",
        "// Line_Reference 33:                     f\"continue.\")",
        "// Line_Reference 36:                 \"secure storage location %s already mounted on tmpfs\" % secdir)",
        "// Line_Reference 38:     logger.debug(\"secure storage location %s not mounted \" % secdir)"
    ]
}
