{
    "cve_id": "CVE-2019-11934",
    "cve_description": "Improper handling of close_notify alerts can result in an out-of-bounds read in AsyncSSLSocket. This issue affects folly prior to v2019.11.04.00.",
    "cve_publish_date": "2019-12-04",
    "cwe_id": "CWE-125",
    "cwe_name": "Out-of-bounds Read",
    "cwe_description": "The product reads data past the end, or before the beginning, of the intended buffer.",
    "commit_message": "Handle close_notify as standard writeErr in AsyncSSLSocket.\n\nSummary: Fixes CVE-2019-11934\n\nReviewed By: mingtaoy\n\nDifferential Revision: D18020613\n\nfbshipit-source-id: db82bb250e53f0d225f1280bd67bc74abd417836",
    "type_of_change": "Modification",
    "filename_of_changes": "AsyncSSLSocket.cpp",
    "code_language": "C++",
    "number_of_lines_added_for_mitigation": "1",
    "number_of_lines_deleted_vulnerable_to_cve": "7",
    "vulnerable_lines": [
        "// Line_Reference 1453:     if (zero_return(error, rc, errno)) {",
        "// Line_Reference 1454:       return WriteResult(0);",
        "// Line_Reference 1455:     }",
        "// Line_Reference 1592:       auto writeResult = interpretSSLError(int(bytes), error);",
        "// Line_Reference 1593:       if (writeResult.writeReturn < 0) {",
        "// Line_Reference 1594:         return writeResult;",
        "// Line_Reference 1595:       } // else fall through to below to correctly record totalWritten"
    ]
}
