{
    "cve_id": "CVE-2019-15149",
    "cve_description": "core.py in Mitogen before 0.2.8 has a typo that drops the unidirectional-routing protection mechanism in the case of a child that is initiated by another child. The Ansible extension is unaffected. NOTE: the vendor disputes this issue because it is exploitable only in conjunction with hypothetical other factors, i.e., an affected use case within a library caller, and a bug in the message receiver policy code that led to reliance on this extra protection mechanism",
    "cve_publish_date": "2019-08-18",
    "cwe_id": "CWE-254",
    "cwe_name": "7PK - Security Features",
    "cwe_description": "Software security is not security software. Here we're concerned with topics like authentication, access control, confidentiality, cryptography, and privilege management.",
    "commit_message": "[security] core: undirectional routing wasn't respected in some cases\n\nWhen creating a context using Router.method(via=somechild),\nunidirectional mode was set on the new child correctly, however if the\nchild were to call Router.method(), due to a typing mistake the new\nchild would start without it.\n\nThis doesn't impact the Ansible extension, as only forked tasks are\nstarted directly by children, and they are not responsible for routing\nmessages.\n\nAdd test so it can't happen again.",
    "type_of_change": "Modification",
    "filename_of_changes": "router_test.py",
    "code_language": "Python",
    "number_of_lines_added_for_mitigation": "35",
    "number_of_lines_deleted_vulnerable_to_cve": "13",
    "vulnerable_lines": [
        "// Line_Reference 345:     def test_siblings_cant_talk(self):",
        "// Line_Reference 347:         l1 = self.router.local()",
        "// Line_Reference 348:         l2 = self.router.local()",
        "// Line_Reference 349:         logs = testlib.LogCapturer()",
        "// Line_Reference 350:         logs.start()",
        "// Line_Reference 351:         e = self.assertRaises(mitogen.core.CallError,",
        "// Line_Reference 352:                               lambda: l2.call(ping_context, l1))",
        "// Line_Reference 354:         msg = self.router.unidirectional_msg % (",
        "// Line_Reference 355:             l2.context_id,",
        "// Line_Reference 356:             l1.context_id,",
        "// Line_Reference 357:         )",
        "// Line_Reference 358:         self.assertTrue(msg in str(e))",
        "// Line_Reference 359:         self.assertTrue('routing mode prevents forward of ' in logs.stop())"
    ]
}
