{
    "cve_id": "CVE-2022-25761",
    "cve_description": "The package open62541/open62541 before 1.2.5, from 1.3-rc1 and before 1.3.1 are vulnerable to Denial of Service (DoS) due to a missing limitation on the number of received chunks - per single session or in total for all concurrent sessions. An attacker can exploit this vulnerability by sending an unlimited number of huge chunks (e.g. 2GB each) without sending the Final closing chunk.",
    "cve_publish_date": "2022-08-23",
    "cwe_id": "CWE-770",
    "cwe_name": "Allocation of Resources Without Limits or Throttling",
    "cwe_description": "The product allocates a reusable resource or group of resources on behalf of an actor without imposing any restrictions on the size or number of resources that can be allocated, in violation of the intended security policy for that actor.",
    "commit_message": "fix(plugin): Add default limits for chunks and message size\n\nBased on a reported DoS vulnerability reported by Team82 (Claroty\nResearch).",
    "type_of_change": "Modification",
    "filename_of_changes": "ua_config_default.c",
    "code_language": "C",
    "number_of_lines_added_for_mitigation": "7",
    "number_of_lines_deleted_vulnerable_to_cve": "7",
    "vulnerable_lines": [
        "// Line_Reference 62:     0,     /* .protocolVersion */",
        "// Line_Reference 63:     65535, /* .sendBufferSize, 64k per chunk */",
        "// Line_Reference 64:     65535, /* .recvBufferSize, 64k per chunk */",
        "// Line_Reference 65:     0,     /* .localMaxMessageSize, 0 -> unlimited */",
        "// Line_Reference 66:     0,     /* .remoteMaxMessageSize, 0 -> unlimited */",
        "// Line_Reference 67:     0,     /* .localMaxChunkCount, 0 -> unlimited */",
        "// Line_Reference 68:     0      /* .remoteMaxChunkCount, 0 -> unlimited */"
    ]
}
