{
    "cve_id": "CVE-2021-4118",
    "cve_description": "pytorch-lightning is vulnerable to Deserialization of Untrusted Data",
    "cve_publish_date": "2021-12-23",
    "cwe_id": "CWE-502",
    "cwe_name": "Deserialization of Untrusted Data",
    "cwe_description": "The product deserializes untrusted data without sufficiently verifying that the resulting data will be valid.",
    "commit_message": "Fix CVE-2020-1747 and CVE-2020-14343 (#11099)",
    "type_of_change": "Modification",
    "filename_of_changes": "saving.py",
    "code_language": "Python",
    "number_of_lines_added_for_mitigation": "1",
    "number_of_lines_deleted_vulnerable_to_cve": "1",
    "vulnerable_lines": [
        "// Line_Reference 347:         hparams = yaml.load(fp, Loader=yaml.UnsafeLoader)"
    ]
}
