{
    "cve_id": "CVE-2021-29421",
    "cve_description": "models/metadata.py in the pikepdf package 1.3.0 through 2.9.2 for Python allows XXE when parsing XMP metadata entries.",
    "cve_publish_date": "2021-04-01",
    "cwe_id": "CWE-611",
    "cwe_name": "Improper Restriction of XML External Entity Reference",
    "cwe_description": "The product processes an XML document that can contain XML entities with URIs that resolve to documents outside of the intended sphere of control, causing the product to embed incorrect documents into its output.",
    "commit_message": "Fix XXE vulnerability in XMP metadata parsing\n\nFor details:\nhttps://portswigger.net/web-security/xxe\n\nReported by: Eric Therond eric.therond@sonarsource.com) of Sonarsource (https://www.sonarsource.com/)",
    "type_of_change": "ModificationType.ADD",
    "filename_of_changes": "metadata.py",
    "code_language": "Python",
    "number_of_lines_added_for_mitigation": "5",
    "number_of_lines_deleted_vulnerable_to_cve": "5",
    "vulnerable_lines": [
        "// Line_Reference 29: from lxml.etree import QName, XMLParser, XMLSyntaxError, parse",
        "// Line_Reference 416:             return parse(BytesIO(xml))",
        "// Line_Reference 419:             return parse(BytesIO(re_xml_illegal_bytes.sub(b'', xml)))",
        "// Line_Reference 422:             parser = XMLParser(recover=True)",
        "// Line_Reference 423:             return parse(BytesIO(xml), parser)"
    ]
}
