{
    "cve_id": "CVE-2022-37451",
    "cve_description": "Exim before 4.96 has an invalid free in pam_converse in auths/call_pam.c because store_free is not used after store_malloc.",
    "cve_publish_date": "2022-08-06",
    "cwe_id": "CWE-763",
    "cwe_name": "Release of Invalid Pointer or Reference",
    "cwe_description": "The product attempts to return a memory resource to the system, but it calls the wrong release function or calls the appropriate release function incorrectly.",
    "commit_message": "Fix PAM auth.  Bug 2813",
    "type_of_change": "Modification",
    "filename_of_changes": "call_pam.c",
    "code_language": "C",
    "number_of_lines_added_for_mitigation": "1",
    "number_of_lines_deleted_vulnerable_to_cve": "1",
    "vulnerable_lines": [
        "// Line_Reference 91:       reply[i].resp = CS string_copy_malloc(arg); /* PAM frees resp */"
    ]
}
