{
    "cve_id": "CVE-2022-35937",
    "cve_description": "TensorFlow is an open source platform for machine learning. The `GatherNd` function takes arguments that determine the sizes of inputs and outputs. If the inputs given are greater than or equal to the sizes of the outputs, an out-of-bounds memory read is triggered. This issue has been patched in GitHub commit 595a65a3e224a0362d7e68c2213acfc2b499a196. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
    "cve_publish_date": "2022-09-16",
    "cwe_id": "CWE-125",
    "cwe_name": "Out-of-bounds Read",
    "cwe_description": "The product reads data past the end, or before the beginning, of the intended buffer.",
    "commit_message": "Return a TFLite error if gather_nd will result in reading invalid memory\n\nPiperOrigin-RevId: 463054033",
    "type_of_change": "Modification",
    "filename_of_changes": "reference_ops.h",
    "code_language": "C++",
    "number_of_lines_added_for_mitigation": "15",
    "number_of_lines_deleted_vulnerable_to_cve": "6",
    "vulnerable_lines": [
        "// Line_Reference 599: inline void GatherNd(const RuntimeShape& params_shape,",
        "// Line_Reference 600:                      const ParamsT* params_data,",
        "// Line_Reference 601:                      const RuntimeShape& indices_shape,",
        "// Line_Reference 602:                      const IndicesT* indices_data,",
        "// Line_Reference 603:                      const RuntimeShape& output_shape, ParamsT* output_data) {",
        "// Line_Reference 608:     int from_pos = 0;"
    ]
}
