{
    "cve_id": "CVE-2022-35993",
    "cve_description": "TensorFlow is an open source platform for machine learning. When `SetSize` receives an input `set_shape` that is not a 1D tensor, it gives a `CHECK` fails that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit cf70b79d2662c0d3c6af74583641e345fc939467. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
    "cve_publish_date": "2022-09-16",
    "cwe_id": "CWE-617",
    "cwe_name": "Reachable Assertion",
    "cwe_description": "The product contains an assert() or similar statement that can be triggered by an attacker, which leads to an application exit or other behavior that is more severe than necessary.",
    "commit_message": "Fix tf.raw_ops.SetSize vulnerability with invalid input arg specifying shape.\n\nCheck that given input is a 1D tensor, as required.\n\nPiperOrigin-RevId: 460740463",
    "type_of_change": "Modification",
    "filename_of_changes": "set_kernels.cc",
    "code_language": "C++",
    "number_of_lines_added_for_mitigation": "6",
    "number_of_lines_deleted_vulnerable_to_cve": "2",
    "vulnerable_lines": [
        "// Line_Reference 73:   TF_RETURN_IF_ERROR(TensorShape::BuildTensorShape(",
        "// Line_Reference 74:       ctx->input(base_index + 2).vec<int64_t>(), &shape));"
    ]
}
